* Few-Shot learning for fashion

In this repository I will experiment with applying few-shot learning to the [[https://www.kaggle.com/paramaggarwal/fashion-product-images-dataset/version/1][Kaggle fashion dataset]] using TensorFlow and Keras.

** Setup

You will need Python >= 3.6, pipenv and preferably access to a GPU. 

The dataset should be unzipped to ~datasets/fashion-dataset~, i.e., after extraction you should have a ~datasets/fashion-dataset/images~ folder and a ~datasets/fashion-dataset/styles.csv~ file.
I've had corruption errors when uncompressing the dataset on CentOS.
It works fine on a mac, however.

** Prototypical Networks

This implementation of [[https://arxiv.org/abs/1703.05175][Prototypical Networks for Few-shot Learning]] by Snell, Swersky and Zemel is heavily inspired by [[https://github.com/oscarknagg/few-shot/][Oscar Knagg's implementation]].

*** Omniglot

As a sanity check for my implementation, I've ran a 5-way, 1-shot experiment on [[https://github.com/brendenlake/omniglot/blob/master/python/images_evaluation.zip][Omniglot]] and managed to replicate the results. Follow these steps to run this experiment:
- First download the dataset and process it with Oscar's ~prepare_omniglot.py~.
- Place the processed dataset under ~datasets/Omniglot~.
- Call ~pipenv run python -m few_shot.experiments.omniglot~.

This takes around 20 minutes to train and evaluate on a GeForce 960.

*** TODO Reference model

**** TODO Image pipeline

**** TODO Train / test split
**** TODO Run the same embedding model as in the paper.
